### ISSUE TITLE
Client library issue: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error

### ISSUE THREAD

**Issue by brian-chung-dragon** [googleapis/nodejs-dialogflow-cx#303]
Environment details
OS: Mac OS Monterey version 12.5
Node.js version: v16.13.0
npm version: 8.1.0
@google-cloud/dialogflow-cx version: 2.15.0

I am trying to run the sample
https://github.com/googleapis/nodejs-dialogflow-cx/blob/main/samples/detect-intent-event.js

And the system returns
```
Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
    at Object.callErrorFromStatus (/Users/brian.chung/Repository/contact-centre-twilio-assets/twilio-console/run-time/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/Users/brian.chung/Repository/contact-centre-twilio-assets/twilio-console/run-time/node_modules/@grpc/grpc-js/src/client.ts:352:36)
    at Object.onReceiveStatus (/Users/brian.chung/Repository/contact-centre-twilio-assets/twilio-console/run-time/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
    at Object.onReceiveStatus (/Users/brian.chung/Repository/contact-centre-twilio-assets/twilio-console/run-time/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
```

**Comment by brian-chung-dragon** [comment]
Maybe the issue is related to my local environment. If I run the same function in serverless environment (AWS) and works completely fine.
