### ISSUE TITLE
Problem when calling the train flow progress

### ISSUE THREAD

**Issue by slimovic** [googleapis/nodejs-dialogflow-cx#78]
I'm facing an issue with the xx library for nodejs, mainly when want to train a flow and to check the progress:

```
const [operation] = await this.flowClient.trainFlow({name: flow})

// this give the error bellow 
const decodedOperation = await this.flowClient.checkTrainFlowProgress(operation.name as string); 

// same with this one
const [response]= await operation.promise();

```
And this is the error:

```
RangeError: index out of range: 12 + 10 > 12
    at indexOutOfRange (/home/app/node_modules/protobufjs/src/reader.js:13:12)
    at BufferReader.read_uint32 [as uint32] (/home/app/node_modules/protobufjs/src/reader.js:98:19)
    at Type.Value$decode [as decode] (eval at Codegen (/home/app/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:8:11)
    at Type.decode_setup [as decode] (/home/app/node_modules/protobufjs/src/type.js:507:25)
    at Type.Struct$decode [as decode] (eval at Codegen (/home/app/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:21:18)
    at Type.decode_setup [as decode] (/home/app/node_modules/protobufjs/src/type.js:507:25)
    at Operation._unpackResponse (/home/app/node_modules/google-gax/src/longRunningCalls/longrunning.ts:227:19)
    at new Operation (/home/app/node_modules/google-gax/src/longRunningCalls/longrunning.ts:91:10)
    at FlowsClient.checkTrainFlowProgress (/home/app/node_modules/@google-cloud/dialogflow-cx/src/v3/flows_client.ts:1168:29)
```

1) Is this a client library issue or a product issue?
This is the client library for dialogflowcx

2) Did someone already solve this?
I did not find yet an answer

3) Do you have a support contract?
nope

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Linux
  - Node.js version: 14.16
  - npm version: 6.14.11
  - `@google-cloud/dialogflow-cx` version: 2.4.0

#### Steps to reproduce

  1. When I try to train the flow and check the progress

Thanks!

**Comment by munkhuushmgl** [comment]
Ok I was not able to reproduce. 

With the following snippet, I was able to check the TrainFlowProgress 

```

  // Imports the Google Cloud Some API library
  const { FlowsClient } = require( '@google-cloud/dialogflow-cx' );
  const STANDARAD = require( '@google-cloud/dialogflow-cx' ).protos.google.cloud.dialogflow.cx.v3.NluSettings.ModelType.MODEL_TYPE_STANDARD;
  /**
   * Example for regional endpoint:
   *   const location = 'us-central1'
   *   const client = new SessionsClient({apiEndpoint: 'us-central1-dialogflow.googleapis.com'})
   */
   const client = new FlowsClient( { apiEndpoint: 'us-central1-dialogflow.googleapis.com' } );

  const nluSetting = {
    modelType: STANDARAD,
    classificationThreshold: 0.3,
    modelTrainingMode: 1
  }
  // create training flow
  const flowRequest = {
    displayName: 'FlowTest',
    description: 'description',
    nluSettings: nluSetting
  }
  const parent = client.agentPath( projectId, location, agentId );

  const createFlowRequest = {
    parent: parent,
    flow: flowRequest,
    languageCode: 'en'
  };

  const [ flow ] = await client.createFlow( createFlowRequest );
  console.log( "================================" );
  console.log( flow );
  console.log( "================================" );


  // name: 'projects/long-door-651/locations/us-cent
  // ral1/agents/1e6aafbb-df13-4c30-8dfb-fb4520ba17e9/flows/70c05796-7a9b-4318-b713-c2bd52df667d

  console.log( flow.name );
  const [ operation_flow ] = await client.trainFlow( { name: flow.name } );
  console.log( "=============START===================" );

  console.log( operation_flow.name );
  console.log( "=============END===================" );

  async function checkTrainFlow ()
  {
    const flowResponse = await client.checkTrainFlowProgress(  operation_flow.name );
    console.log( flowResponse );
    
  }
  checkTrainFlow();
```

**Comment by munkhuushmgl** [comment]
Feel free to reopen this if u still experieincing same issue.

With this snippet, you should able to check flow progress
